### ISSUE TITLE
Decimal precision can lead to transactions not processing (user inputs more than available quantity)

### ISSUE THREAD

**Issue by LinksterMJ** [spartan-protocol/spartanpools-dapp#195]
Observation: 
The quantities are often displayed to 2 or sometimes 3 decimal places.
Possibly being truncated or rounded.
However this can cause the user to input more than 100% of a token quantity to be nominated for pooling (and possibly a swap), which then causes Metamask not to be triggered, giving the user the impression that nothing is happening.
Workaround seems to be manually entering slightly less than 100% for the transaction to be accepted for Metamask approval.
Problem is this is inefficient for the user (requires manual intervention), causes user confusion, could lead to user rejection and abandonment of the Sparta portal, and can result in residual dust quantities being left behind.

Request:
Would it be possible to display to the full decimal precision of each token, to ensure 100% accuracy, and the ability to avoid "dust" by needing to enter slightly less than 100%? 
- would be ok to drop redundant zeros
- may be necessary to round up the quantity to the nearest 1/6th or 1/18th when a user is preparing a swap, pool operation etc.

**Comment by SamusElderg** [comment]
@LinksterMJ all txn related calculations use gwei big numbers and are not formatted so there is no rounding. 

However i have investigated your above issue and it applies only to the BNB pool. It is due to BNB used for gas (not being removed from the 100% calc)

I think this is already an issue but ill put a fix in place now and close this soon 👍 thanks for putting up the issue! I appreciate it!
