### ISSUE TITLE
Button fill colour of Lock token not resetting

### ISSUE THREAD

**Issue by LinksterMJ** [spartan-protocol/spartanpools-dapp#199]
Observation: After locking additional tokens, I noticed that the blue colour of the Lock button had not reset to a lighter blue.

![Blue colour of Lock button](https://user-images.githubusercontent.com/34363031/97435955-4dad4080-1975-11eb-95a1-af968f7431d3.JPG)

**Comment by SamusElderg** [comment]
@f1ntch this is due to the 'active:' state being a 'toggle'.
It doesnt clear until you click anywhere else.

Not sure if you have an easy way around this?
Maybe just create a special className for buttons like this ('non-active-toggle') or something like that with a higher priority background colour than the ':active' css rule for that button or just apply '!important' to a unique ID/classname?
